services:
  openhab:
    image: "openhab/openhab:4.2.1"
    container_name: openhab
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "./openhab_addons:/openhab/addons"
      - "./openhab_conf:/openhab/conf"
      - "./openhab_userdata:/openhab/userdata"
    environment:
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - simulator
      - mosquitto
      - modbus-simulator

  simulator:
    image: python:3.10-slim
    container_name: simulator
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - "./simulator:/app"
    working_dir: /app
    command: sh -c "pip install flask && python app.py"

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data:/mosquitto/data"
      - "./mosquitto/log:/mosquitto/log"
      - "./mosquitto/certs:/mosquitto/certs"

  modbus-simulator:
    build: ./modbus-server
    container_name: modbus-simulator
    restart: unless-stopped
    ports:
      - "502:502"

  mistral-forecast:
    build: ./forecast
    container_name: mistral-api
    restart: unless-stopped
    environment:
      - OPENHAB_TOKEN=oh.mistralscript.cJ9k767gKXzXZconUPKjOpxGwYNB5cPnFXG77VIuYmevQbT08vyXtX3OpGOUxQ2bQf4USoEdh4nFtls0uhtYkA
      - MISTRAL_TOKEN=iUV6aOIyWy6v38Ghsur2Vw0hdknVyHpk
    depends_on:
      - openhab